/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Backend": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "BetterAuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Email": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "EmbeddingQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "Frontend": {
      "type": "sst.aws.Router"
      "url": string
    }
    "GitHubAppSlug": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GitHubClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GitHubClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GitHubPrivateKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleAiStudioApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Landing": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "LydieApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OpenAiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PolarApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PolarProProductId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PolarWebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PostgresConnectionStringDirect": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PostgresConnectionStringPooled": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ReplicationManager": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "ShopifyClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ShopifyClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Web": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "Zero": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "ZeroAdminPassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "replication-bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "vpc": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}