/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AssetsRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "Backend": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "Email": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "Marketing": {
      "type": "sst.aws.Astro"
      "url": string
    }
    "OnboardingEmailProcessorFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "OrganizationAssets": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Web": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "WorkspaceExportProcessorFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "WorkspaceExports": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Zero": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "vpc": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}