/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteRouteImport } from './routes/_landing/route'
import { Route as _authRouteRouteImport } from './routes/__auth/route'
import { Route as _authIndexRouteImport } from './routes/__auth/index'
import { Route as LandingBlogIndexRouteImport } from './routes/_landing/blog/index'
import { Route as LandingAuthIndexRouteImport } from './routes/_landing/auth/index'
import { Route as _authOnboardingIndexRouteImport } from './routes/__auth/onboarding/index'
import { Route as _authWOrganizationIdRouteRouteImport } from './routes/__auth/w/$organizationId/route'
import { Route as _authWOrganizationIdIndexRouteImport } from './routes/__auth/w/$organizationId/index'
import { Route as _authWOrganizationIdAssistantRouteImport } from './routes/__auth/w/$organizationId/assistant'
import { Route as _authWOrganizationIdSettingsRouteRouteImport } from './routes/__auth/w/$organizationId/settings/route'
import { Route as _authWOrganizationIdSettingsIndexRouteImport } from './routes/__auth/w/$organizationId/settings/index'
import { Route as _authWOrganizationIdIdIndexRouteImport } from './routes/__auth/w/$organizationId/$id/index'
import { Route as _authWOrganizationIdSettingsUserRouteImport } from './routes/__auth/w/$organizationId/settings/user'
import { Route as _authWOrganizationIdSettingsImportRouteImport } from './routes/__auth/w/$organizationId/settings/import'
import { Route as _authWOrganizationIdSettingsComponentsRouteImport } from './routes/__auth/w/$organizationId/settings/components'
import { Route as _authWOrganizationIdSettingsBillingRouteImport } from './routes/__auth/w/$organizationId/settings/billing'
import { Route as _authWOrganizationIdSettingsAiRouteImport } from './routes/__auth/w/$organizationId/settings/ai'
import { Route as _authWOrganizationIdSettingsIntegrationsIndexRouteImport } from './routes/__auth/w/$organizationId/settings/integrations/index'
import { Route as _authWOrganizationIdSettingsIntegrationsGithubRouteImport } from './routes/__auth/w/$organizationId/settings/integrations/github'

const LandingRouteRoute = LandingRouteRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const _authRouteRoute = _authRouteRouteImport.update({
  id: '/__auth',
  getParentRoute: () => rootRouteImport,
} as any)
const _authIndexRoute = _authIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _authRouteRoute,
} as any)
const LandingBlogIndexRoute = LandingBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LandingRouteRoute,
} as any)
const LandingAuthIndexRoute = LandingAuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => LandingRouteRoute,
} as any)
const _authOnboardingIndexRoute = _authOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authWOrganizationIdRouteRoute =
  _authWOrganizationIdRouteRouteImport.update({
    id: '/w/$organizationId',
    path: '/w/$organizationId',
    getParentRoute: () => _authRouteRoute,
  } as any)
const _authWOrganizationIdIndexRoute =
  _authWOrganizationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => _authWOrganizationIdRouteRoute,
  } as any)
const _authWOrganizationIdAssistantRoute =
  _authWOrganizationIdAssistantRouteImport.update({
    id: '/assistant',
    path: '/assistant',
    getParentRoute: () => _authWOrganizationIdRouteRoute,
  } as any)
const _authWOrganizationIdSettingsRouteRoute =
  _authWOrganizationIdSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => _authWOrganizationIdRouteRoute,
  } as any)
const _authWOrganizationIdSettingsIndexRoute =
  _authWOrganizationIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => _authWOrganizationIdSettingsRouteRoute,
  } as any)
const _authWOrganizationIdIdIndexRoute =
  _authWOrganizationIdIdIndexRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => _authWOrganizationIdRouteRoute,
  } as any)
const _authWOrganizationIdSettingsUserRoute =
  _authWOrganizationIdSettingsUserRouteImport.update({
    id: '/user',
    path: '/user',
    getParentRoute: () => _authWOrganizationIdSettingsRouteRoute,
  } as any)
const _authWOrganizationIdSettingsImportRoute =
  _authWOrganizationIdSettingsImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => _authWOrganizationIdSettingsRouteRoute,
  } as any)
const _authWOrganizationIdSettingsComponentsRoute =
  _authWOrganizationIdSettingsComponentsRouteImport.update({
    id: '/components',
    path: '/components',
    getParentRoute: () => _authWOrganizationIdSettingsRouteRoute,
  } as any)
const _authWOrganizationIdSettingsBillingRoute =
  _authWOrganizationIdSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => _authWOrganizationIdSettingsRouteRoute,
  } as any)
const _authWOrganizationIdSettingsAiRoute =
  _authWOrganizationIdSettingsAiRouteImport.update({
    id: '/ai',
    path: '/ai',
    getParentRoute: () => _authWOrganizationIdSettingsRouteRoute,
  } as any)
const _authWOrganizationIdSettingsIntegrationsIndexRoute =
  _authWOrganizationIdSettingsIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => _authWOrganizationIdSettingsRouteRoute,
  } as any)
const _authWOrganizationIdSettingsIntegrationsGithubRoute =
  _authWOrganizationIdSettingsIntegrationsGithubRouteImport.update({
    id: '/integrations/github',
    path: '/integrations/github',
    getParentRoute: () => _authWOrganizationIdSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof _authIndexRoute
  '/w/$organizationId': typeof _authWOrganizationIdRouteRouteWithChildren
  '/onboarding': typeof _authOnboardingIndexRoute
  '/auth': typeof LandingAuthIndexRoute
  '/blog': typeof LandingBlogIndexRoute
  '/w/$organizationId/settings': typeof _authWOrganizationIdSettingsRouteRouteWithChildren
  '/w/$organizationId/assistant': typeof _authWOrganizationIdAssistantRoute
  '/w/$organizationId/': typeof _authWOrganizationIdIndexRoute
  '/w/$organizationId/settings/ai': typeof _authWOrganizationIdSettingsAiRoute
  '/w/$organizationId/settings/billing': typeof _authWOrganizationIdSettingsBillingRoute
  '/w/$organizationId/settings/components': typeof _authWOrganizationIdSettingsComponentsRoute
  '/w/$organizationId/settings/import': typeof _authWOrganizationIdSettingsImportRoute
  '/w/$organizationId/settings/user': typeof _authWOrganizationIdSettingsUserRoute
  '/w/$organizationId/$id': typeof _authWOrganizationIdIdIndexRoute
  '/w/$organizationId/settings/': typeof _authWOrganizationIdSettingsIndexRoute
  '/w/$organizationId/settings/integrations/github': typeof _authWOrganizationIdSettingsIntegrationsGithubRoute
  '/w/$organizationId/settings/integrations': typeof _authWOrganizationIdSettingsIntegrationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof _authIndexRoute
  '/onboarding': typeof _authOnboardingIndexRoute
  '/auth': typeof LandingAuthIndexRoute
  '/blog': typeof LandingBlogIndexRoute
  '/w/$organizationId/assistant': typeof _authWOrganizationIdAssistantRoute
  '/w/$organizationId': typeof _authWOrganizationIdIndexRoute
  '/w/$organizationId/settings/ai': typeof _authWOrganizationIdSettingsAiRoute
  '/w/$organizationId/settings/billing': typeof _authWOrganizationIdSettingsBillingRoute
  '/w/$organizationId/settings/components': typeof _authWOrganizationIdSettingsComponentsRoute
  '/w/$organizationId/settings/import': typeof _authWOrganizationIdSettingsImportRoute
  '/w/$organizationId/settings/user': typeof _authWOrganizationIdSettingsUserRoute
  '/w/$organizationId/$id': typeof _authWOrganizationIdIdIndexRoute
  '/w/$organizationId/settings': typeof _authWOrganizationIdSettingsIndexRoute
  '/w/$organizationId/settings/integrations/github': typeof _authWOrganizationIdSettingsIntegrationsGithubRoute
  '/w/$organizationId/settings/integrations': typeof _authWOrganizationIdSettingsIntegrationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__auth': typeof _authRouteRouteWithChildren
  '/_landing': typeof LandingRouteRouteWithChildren
  '/__auth/': typeof _authIndexRoute
  '/__auth/w/$organizationId': typeof _authWOrganizationIdRouteRouteWithChildren
  '/__auth/onboarding/': typeof _authOnboardingIndexRoute
  '/_landing/auth/': typeof LandingAuthIndexRoute
  '/_landing/blog/': typeof LandingBlogIndexRoute
  '/__auth/w/$organizationId/settings': typeof _authWOrganizationIdSettingsRouteRouteWithChildren
  '/__auth/w/$organizationId/assistant': typeof _authWOrganizationIdAssistantRoute
  '/__auth/w/$organizationId/': typeof _authWOrganizationIdIndexRoute
  '/__auth/w/$organizationId/settings/ai': typeof _authWOrganizationIdSettingsAiRoute
  '/__auth/w/$organizationId/settings/billing': typeof _authWOrganizationIdSettingsBillingRoute
  '/__auth/w/$organizationId/settings/components': typeof _authWOrganizationIdSettingsComponentsRoute
  '/__auth/w/$organizationId/settings/import': typeof _authWOrganizationIdSettingsImportRoute
  '/__auth/w/$organizationId/settings/user': typeof _authWOrganizationIdSettingsUserRoute
  '/__auth/w/$organizationId/$id/': typeof _authWOrganizationIdIdIndexRoute
  '/__auth/w/$organizationId/settings/': typeof _authWOrganizationIdSettingsIndexRoute
  '/__auth/w/$organizationId/settings/integrations/github': typeof _authWOrganizationIdSettingsIntegrationsGithubRoute
  '/__auth/w/$organizationId/settings/integrations/': typeof _authWOrganizationIdSettingsIntegrationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/w/$organizationId'
    | '/onboarding'
    | '/auth'
    | '/blog'
    | '/w/$organizationId/settings'
    | '/w/$organizationId/assistant'
    | '/w/$organizationId/'
    | '/w/$organizationId/settings/ai'
    | '/w/$organizationId/settings/billing'
    | '/w/$organizationId/settings/components'
    | '/w/$organizationId/settings/import'
    | '/w/$organizationId/settings/user'
    | '/w/$organizationId/$id'
    | '/w/$organizationId/settings/'
    | '/w/$organizationId/settings/integrations/github'
    | '/w/$organizationId/settings/integrations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/auth'
    | '/blog'
    | '/w/$organizationId/assistant'
    | '/w/$organizationId'
    | '/w/$organizationId/settings/ai'
    | '/w/$organizationId/settings/billing'
    | '/w/$organizationId/settings/components'
    | '/w/$organizationId/settings/import'
    | '/w/$organizationId/settings/user'
    | '/w/$organizationId/$id'
    | '/w/$organizationId/settings'
    | '/w/$organizationId/settings/integrations/github'
    | '/w/$organizationId/settings/integrations'
  id:
    | '__root__'
    | '/__auth'
    | '/_landing'
    | '/__auth/'
    | '/__auth/w/$organizationId'
    | '/__auth/onboarding/'
    | '/_landing/auth/'
    | '/_landing/blog/'
    | '/__auth/w/$organizationId/settings'
    | '/__auth/w/$organizationId/assistant'
    | '/__auth/w/$organizationId/'
    | '/__auth/w/$organizationId/settings/ai'
    | '/__auth/w/$organizationId/settings/billing'
    | '/__auth/w/$organizationId/settings/components'
    | '/__auth/w/$organizationId/settings/import'
    | '/__auth/w/$organizationId/settings/user'
    | '/__auth/w/$organizationId/$id/'
    | '/__auth/w/$organizationId/settings/'
    | '/__auth/w/$organizationId/settings/integrations/github'
    | '/__auth/w/$organizationId/settings/integrations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _authRouteRoute: typeof _authRouteRouteWithChildren
  LandingRouteRoute: typeof LandingRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LandingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth': {
      id: '/__auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth/': {
      id: '/__auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _authIndexRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/_landing/blog/': {
      id: '/_landing/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof LandingBlogIndexRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/auth/': {
      id: '/_landing/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof LandingAuthIndexRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/__auth/onboarding/': {
      id: '/__auth/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof _authOnboardingIndexRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__auth/w/$organizationId': {
      id: '/__auth/w/$organizationId'
      path: '/w/$organizationId'
      fullPath: '/w/$organizationId'
      preLoaderRoute: typeof _authWOrganizationIdRouteRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__auth/w/$organizationId/': {
      id: '/__auth/w/$organizationId/'
      path: '/'
      fullPath: '/w/$organizationId/'
      preLoaderRoute: typeof _authWOrganizationIdIndexRouteImport
      parentRoute: typeof _authWOrganizationIdRouteRoute
    }
    '/__auth/w/$organizationId/assistant': {
      id: '/__auth/w/$organizationId/assistant'
      path: '/assistant'
      fullPath: '/w/$organizationId/assistant'
      preLoaderRoute: typeof _authWOrganizationIdAssistantRouteImport
      parentRoute: typeof _authWOrganizationIdRouteRoute
    }
    '/__auth/w/$organizationId/settings': {
      id: '/__auth/w/$organizationId/settings'
      path: '/settings'
      fullPath: '/w/$organizationId/settings'
      preLoaderRoute: typeof _authWOrganizationIdSettingsRouteRouteImport
      parentRoute: typeof _authWOrganizationIdRouteRoute
    }
    '/__auth/w/$organizationId/settings/': {
      id: '/__auth/w/$organizationId/settings/'
      path: '/'
      fullPath: '/w/$organizationId/settings/'
      preLoaderRoute: typeof _authWOrganizationIdSettingsIndexRouteImport
      parentRoute: typeof _authWOrganizationIdSettingsRouteRoute
    }
    '/__auth/w/$organizationId/$id/': {
      id: '/__auth/w/$organizationId/$id/'
      path: '/$id'
      fullPath: '/w/$organizationId/$id'
      preLoaderRoute: typeof _authWOrganizationIdIdIndexRouteImport
      parentRoute: typeof _authWOrganizationIdRouteRoute
    }
    '/__auth/w/$organizationId/settings/user': {
      id: '/__auth/w/$organizationId/settings/user'
      path: '/user'
      fullPath: '/w/$organizationId/settings/user'
      preLoaderRoute: typeof _authWOrganizationIdSettingsUserRouteImport
      parentRoute: typeof _authWOrganizationIdSettingsRouteRoute
    }
    '/__auth/w/$organizationId/settings/import': {
      id: '/__auth/w/$organizationId/settings/import'
      path: '/import'
      fullPath: '/w/$organizationId/settings/import'
      preLoaderRoute: typeof _authWOrganizationIdSettingsImportRouteImport
      parentRoute: typeof _authWOrganizationIdSettingsRouteRoute
    }
    '/__auth/w/$organizationId/settings/components': {
      id: '/__auth/w/$organizationId/settings/components'
      path: '/components'
      fullPath: '/w/$organizationId/settings/components'
      preLoaderRoute: typeof _authWOrganizationIdSettingsComponentsRouteImport
      parentRoute: typeof _authWOrganizationIdSettingsRouteRoute
    }
    '/__auth/w/$organizationId/settings/billing': {
      id: '/__auth/w/$organizationId/settings/billing'
      path: '/billing'
      fullPath: '/w/$organizationId/settings/billing'
      preLoaderRoute: typeof _authWOrganizationIdSettingsBillingRouteImport
      parentRoute: typeof _authWOrganizationIdSettingsRouteRoute
    }
    '/__auth/w/$organizationId/settings/ai': {
      id: '/__auth/w/$organizationId/settings/ai'
      path: '/ai'
      fullPath: '/w/$organizationId/settings/ai'
      preLoaderRoute: typeof _authWOrganizationIdSettingsAiRouteImport
      parentRoute: typeof _authWOrganizationIdSettingsRouteRoute
    }
    '/__auth/w/$organizationId/settings/integrations/': {
      id: '/__auth/w/$organizationId/settings/integrations/'
      path: '/integrations'
      fullPath: '/w/$organizationId/settings/integrations'
      preLoaderRoute: typeof _authWOrganizationIdSettingsIntegrationsIndexRouteImport
      parentRoute: typeof _authWOrganizationIdSettingsRouteRoute
    }
    '/__auth/w/$organizationId/settings/integrations/github': {
      id: '/__auth/w/$organizationId/settings/integrations/github'
      path: '/integrations/github'
      fullPath: '/w/$organizationId/settings/integrations/github'
      preLoaderRoute: typeof _authWOrganizationIdSettingsIntegrationsGithubRouteImport
      parentRoute: typeof _authWOrganizationIdSettingsRouteRoute
    }
  }
}

interface _authWOrganizationIdSettingsRouteRouteChildren {
  _authWOrganizationIdSettingsAiRoute: typeof _authWOrganizationIdSettingsAiRoute
  _authWOrganizationIdSettingsBillingRoute: typeof _authWOrganizationIdSettingsBillingRoute
  _authWOrganizationIdSettingsComponentsRoute: typeof _authWOrganizationIdSettingsComponentsRoute
  _authWOrganizationIdSettingsImportRoute: typeof _authWOrganizationIdSettingsImportRoute
  _authWOrganizationIdSettingsUserRoute: typeof _authWOrganizationIdSettingsUserRoute
  _authWOrganizationIdSettingsIndexRoute: typeof _authWOrganizationIdSettingsIndexRoute
  _authWOrganizationIdSettingsIntegrationsGithubRoute: typeof _authWOrganizationIdSettingsIntegrationsGithubRoute
  _authWOrganizationIdSettingsIntegrationsIndexRoute: typeof _authWOrganizationIdSettingsIntegrationsIndexRoute
}

const _authWOrganizationIdSettingsRouteRouteChildren: _authWOrganizationIdSettingsRouteRouteChildren =
  {
    _authWOrganizationIdSettingsAiRoute: _authWOrganizationIdSettingsAiRoute,
    _authWOrganizationIdSettingsBillingRoute:
      _authWOrganizationIdSettingsBillingRoute,
    _authWOrganizationIdSettingsComponentsRoute:
      _authWOrganizationIdSettingsComponentsRoute,
    _authWOrganizationIdSettingsImportRoute:
      _authWOrganizationIdSettingsImportRoute,
    _authWOrganizationIdSettingsUserRoute:
      _authWOrganizationIdSettingsUserRoute,
    _authWOrganizationIdSettingsIndexRoute:
      _authWOrganizationIdSettingsIndexRoute,
    _authWOrganizationIdSettingsIntegrationsGithubRoute:
      _authWOrganizationIdSettingsIntegrationsGithubRoute,
    _authWOrganizationIdSettingsIntegrationsIndexRoute:
      _authWOrganizationIdSettingsIntegrationsIndexRoute,
  }

const _authWOrganizationIdSettingsRouteRouteWithChildren =
  _authWOrganizationIdSettingsRouteRoute._addFileChildren(
    _authWOrganizationIdSettingsRouteRouteChildren,
  )

interface _authWOrganizationIdRouteRouteChildren {
  _authWOrganizationIdSettingsRouteRoute: typeof _authWOrganizationIdSettingsRouteRouteWithChildren
  _authWOrganizationIdAssistantRoute: typeof _authWOrganizationIdAssistantRoute
  _authWOrganizationIdIndexRoute: typeof _authWOrganizationIdIndexRoute
  _authWOrganizationIdIdIndexRoute: typeof _authWOrganizationIdIdIndexRoute
}

const _authWOrganizationIdRouteRouteChildren: _authWOrganizationIdRouteRouteChildren =
  {
    _authWOrganizationIdSettingsRouteRoute:
      _authWOrganizationIdSettingsRouteRouteWithChildren,
    _authWOrganizationIdAssistantRoute: _authWOrganizationIdAssistantRoute,
    _authWOrganizationIdIndexRoute: _authWOrganizationIdIndexRoute,
    _authWOrganizationIdIdIndexRoute: _authWOrganizationIdIdIndexRoute,
  }

const _authWOrganizationIdRouteRouteWithChildren =
  _authWOrganizationIdRouteRoute._addFileChildren(
    _authWOrganizationIdRouteRouteChildren,
  )

interface _authRouteRouteChildren {
  _authIndexRoute: typeof _authIndexRoute
  _authWOrganizationIdRouteRoute: typeof _authWOrganizationIdRouteRouteWithChildren
  _authOnboardingIndexRoute: typeof _authOnboardingIndexRoute
}

const _authRouteRouteChildren: _authRouteRouteChildren = {
  _authIndexRoute: _authIndexRoute,
  _authWOrganizationIdRouteRoute: _authWOrganizationIdRouteRouteWithChildren,
  _authOnboardingIndexRoute: _authOnboardingIndexRoute,
}

const _authRouteRouteWithChildren = _authRouteRoute._addFileChildren(
  _authRouteRouteChildren,
)

interface LandingRouteRouteChildren {
  LandingAuthIndexRoute: typeof LandingAuthIndexRoute
  LandingBlogIndexRoute: typeof LandingBlogIndexRoute
}

const LandingRouteRouteChildren: LandingRouteRouteChildren = {
  LandingAuthIndexRoute: LandingAuthIndexRoute,
  LandingBlogIndexRoute: LandingBlogIndexRoute,
}

const LandingRouteRouteWithChildren = LandingRouteRoute._addFileChildren(
  LandingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _authRouteRoute: _authRouteRouteWithChildren,
  LandingRouteRoute: LandingRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
