/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_ZERO_URL: string;
  readonly VITE_API_URL: string;
  readonly VITE_YJS_SERVER_URL: string;
  readonly VITE_ASSETS_DOMAIN: string;
}
interface ImportMeta {
  readonly env: ImportMetaEnv;
}
